export const data = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    followers: ["Rey.Padberg@karina.biz"],
    imageUrl: "https://picsum.photos/200/300?random=1",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    followers: ["Rey.Padberg@karina.biz"],
    imageUrl: "https://picsum.photos/200/300?random=2",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    followers: ["Rey.Padberg@karina.biz"],
    imageUrl: "https://picsum.photos/200/300?random=3",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    followers: ["Rey.Padberg@karina.biz"],
    imageUrl: "https://picsum.photos/200/300?random=4",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    followers: ["Rey.Padberg@karina.biz"],
    imageUrl: "https://picsum.photos/200/300?random=5",
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    followers: ["Lucio_Hettinger@annie.ca"],
    imageUrl: "https://picsum.photos/200/300?random=6",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    followers: ["Karley_Dach@jasper.info"],
    imageUrl: "https://picsum.photos/200/300?random=7",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    followers: ["Telly.Hoeger@billy.biz"],
    imageUrl: "https://picsum.photos/200/300?random=8",
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
    followers: ["Rey.Padberg@karina.biz"],
    imageUrl: "https://picsum.photos/200/300?random=9",
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    followers: ["Chaim_McDermott@dana.io"],
    imageUrl: "https://picsum.photos/200/300?random=10",
  },
];
